### ISSUE TITLE
Combat Only Disabled // Druid Spiritshape and Chanter chants

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#31] opened 2015-08-31 00:41 UTC
If the combat ends with Spiritshape still on, instead of reverting the druid to normal form it recasts Spiritshape. It then wears off a few seconds later, at which point the druid transforms back to normal. This happens every combat for me. I reverted to the vanilla 2.0 dll and it doesn't happen there. I haven't had a chance to narrow down what specific mod is causing this.

I don't think this is a big enough deal to hold up releasing something, but we will want to take a look at it.

**Comment by GregRos** [comment] 2015-08-31 01:00
...wow. That is a head scratcher. 

Wow.

Sometimes you have an inkling of what caused a bug. Not this time.

Were you running with the combat only disabler?

**Comment by tjayharvey** [comment] 2015-08-31 01:16
Yes. It also seems to affect Kana - he immediately cancels his chant and restarts it, including the first phrase taking affect (according to the combat log). I'll try deactivating combat-only disabler and see if that removes it.

**Comment by tjayharvey** [comment] 2015-08-31 01:22
Yes, unchecking that in Options seems to have fixed it.

**Comment by GregRos** [comment] 2015-08-31 01:34
Ahh I think I know the lines that caused it. It's one of the things I merged from 2.0. I'll work on it after the release is out the door.

**Comment by GregRos** [comment] 2015-08-31 19:34
Is the expected behavior of this feature to end the combat-only abilities at the end of combat, or just not touch them?

**Edit:** Ahh okay, I've investigated this issue further, and from what I've seen, the mod was just never completed. Only some bits of related code were patched.

**Edit2:** Fixed it.

However, even after the fix, this option will remain buggy, and there's not much you can do about it. Casting Wall of Fire for example, doesn't work out of combat (the spell is cast, but then disappears. This is probably caused by the spell itself checking if it's the end of combat, and forcing itself to end). If you save while spirit shaped, when you reload the druid will no longer be in animal form, but he will be equipped with animal claws, and all of his equipment will be gone. The option does warn that this will cause bugs though. Summons also never appear. On the other hand, the fix also allows you to use potions and consumables, which I guess is a good thing. And it comes down to a few statements, and less code is always good.

**Closed as completed** 2015-08-31 22:35 UTC
