### ISSUE TITLE
Small issue with your fork: IEMod.csproj references Mono.Cecil from NuGet

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#22] opened 2015-08-29 18:13 UTC
I noticed this while merging your pull request.

You should remove the reference as it can cause problems when patching (the code in there will be injected into the game after all) and also when merging with this repo.

**Comment by tjayharvey** [comment] 2015-08-29 18:14
Fixed internally. Will push it to my repo when I'm done with the per encounter spells testing.

**Comment by GregRos** [comment] 2015-08-29 18:29
Also, including and excluding files from the project is seriously confusing the repo's diff tools, because they use the order of statements in the file, but VS adds the XML tags without regard to order. So e.g. if I include files X, Y and you include files X, Z the diff tools may not be able to integrate the csproj files correctly. So we should try to avoid doing this too much and instead comment out sections or delete files altogether. It will just make for smoother merging.

We should instead try to keep all the files

**Comment by tjayharvey** [comment] 2015-08-29 18:30
Yeah, at my company we always manually merge project/solution files for that reason. Though not usually because of includes/excludes, but because of new files added. But not sure how to do that (as easily) with git.

**Comment by GregRos** [comment] 2015-08-29 18:35
You just need a full git client, like SmartGit, Sourcetree, etc. They have tools for that (that's how I merged the csproj files, and how I merged the modified game code with the mod). So you can do it, we should just be mindful of the issue. For new files git actually does really well.

**Comment by GregRos** [comment] 2015-08-29 18:41
Ohh one thing we could use is the `DisablePatchingByNameAttribute`. You can write: `[assembly: DisablePatchingByName("regex", PatchingTarget.Type)]` and it will not patch anything that matches the regex. It's handy for not patching entire namespaces, like `DisablePatchingByName(@"^IEMod\.Mods\.AIMod", PatchingTarget.Type)`. So I'll include AI and just disable patching it. Come to think of it, I'm not sure if it's even documented lol.

**Comment by tjayharvey** [comment] 2015-08-29 22:05
I've integrated your version and confirmed that it definitely does not include the NuGet package in mine any more.

**Closed as completed by tjayharvey** 2015-08-29 22:05 UTC
